[WIP] Migrate to JupyterLab 3
NERSC/jupyterlab-favorites pull request #19
Opened 2021-02-26 21:20 UTC by mlhenderson

Updated to work with the current version of JupyterLab 3

Used the migration tool initially to update repo structure and package.json contents for compatibility (most new files in this PR come from this step)
Updated extension version in package.json to 3.0.0
Added sdist, bdist, bdist_wheel to /dist

Code modifications and cleanup:
 - Set classnames to constants in typescript with docstrings for future reference
 - Changed insert behavior for Favorites to be below the FileBrowser toolbar rather than above the BreadCrumbs (new FileBrowser file filtering component is properly grouped under FileBrowser now)
 - Updated CSS for BreadCrumbs Pinner Favorite icon to position it over the correct element
 - Moved contents of index.css to base.css, now index imports base

Remaining items

- [ ] Update README with current install instructions for JupyterLab 3

2021-03-20 12:25 UTC, fcollonval requested changes
@mlhenderson thanks a lot for working on this.

Small review from my side:
- Python package cannot contain `-` in their  name. Could you rename the python folder `jupyterlab_favorites` (+ some other places see my suggestions) ?
- Binary files make it into git. You should remove the files in the `dist` folder. I advice you to add that folder in the .gitignore file to avoid further trouble.

2021-03-20 12:25 UTC, fcollonval commented on MANIFEST.in
> +graft jupyterlab-favorites/labextension
```suggestion
graft jupyterlab_favorites/labextension
```

2021-03-20 12:25 UTC, fcollonval commented on package.json
> +    "clean:labextension": "rimraf jupyterlab-favorites/labextension",
```suggestion
    "clean:labextension": "rimraf jupyterlab_favorites/labextension",
```

2021-03-20 12:25 UTC, fcollonval commented on package.json
> +    "outputDir": "jupyterlab-favorites/labextension"
```suggestion
    "outputDir": "jupyterlab_favorites/labextension"
```

2021-03-20 12:25 UTC, fcollonval commented on setup.py
> +    name=name,
```suggestion
    name=python_name,
```

2021-03-20 12:25 UTC, fcollonval commented on setup.py
> +name = "jupyterlab-favorites"
```suggestion
name = "jupyterlab-favorites"
python_name = name.replace("-", "_")
```

2021-03-20 12:25 UTC, fcollonval commented on setup.py
> +lab_path = (HERE / name / "labextension")
```suggestion
lab_path = (HERE / python_name / "labextension")
```

2021-03-22 16:28 UTC, mlhenderson commented
@fcollonval Committing the binary files was intentional actually (see the PR comments), but I can definitely remove those if it is actually a problem, and then some editing of the README will also be needed.

2021-03-22 17:08 UTC, mlhenderson commented
@fcollonval If this looks good to you now, let me know.

2021-03-23 08:18 UTC, fcollonval commented
This looks good to me

> Committing the binary files was intentional actually (see the PR comments), but I can definitely remove those if it is actually a problem, and then some editing of the README will also be needed.

Sorry I miss that point. This is not recommended as binary files are not playing well with git and they by nature won't be in sync with the repository. Moreover their name will change at each release.

The recommended pattern is to publish them or to attach them to a GitHub release (you can drag & drop them on the release edition page). So the repository status corresponding to those artifacts is clear.

> Note: you can pip install a git repository - https://pip.pypa.io/en/stable/reference/pip_install/#git. If you want to mention that in the README.

2021-03-23 23:20 UTC, mlhenderson commented
Good points, makes sense.  Thanks for the review!

2021-03-23 23:46 UTC, merged

2021-03-24 00:07 UTC, jasongrout commented
Thank you *very* much!